# Generated by Django 4.0.2 on 2022-03-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_icons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iconsPage',
        ),
    ]
