# Generated by Django 4.0.2 on 2022-04-24 18:11

import django.core.validators
from django.db import migrations, models
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_icons', '0002_delete_iconspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='file',
            field=models.FileField(upload_to=wagtail.images.models.get_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='file'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.CharField(max_length=255)),
                ('icons', models.ManyToManyField(to='wagtail_icons.Icon')),
            ],
        ),
    ]
