# Generated by Django 4.0.2 on 2022-04-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_icons', '0003_alter_icon_file_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icons',
            field=models.ManyToManyField(blank=True, null=True, to='wagtail_icons.Icon'),
        ),
    ]
