# Generated by Django 4.0.2 on 2022-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_icons', '0004_alter_group_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icons',
            field=models.ManyToManyField(blank=True, to='wagtail_icons.Icon'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
    ]
