# Generated by Django 4.0.2 on 2022-05-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_icons', '0005_alter_group_icons_alter_group_slug_alter_group_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='edited'),
        ),
    ]
