# Generated by Django 4.0.2 on 2022-06-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_icons', '0006_group_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
